eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka

# Zipkin server configuration
spring:
  zipkin:
    base-url: http://zipkin-server:9411

# Enable Zipkin HTTP sender
spring:
  zipkin:
    sender:
      type: web

# Enable Spring Sleuth
spring:
  sleuth:
    enabled: true
    
management:
  tracing:
    sampling:
      probability: 1.0
